apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: {{ .Values.mariadb.namespace }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.mariadb.secrets.bdd_root_password }}
  mariadb-user-password: {{ .Values.mariadb.secrets.bdd_user_password }}
