apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: {{ .Values.mariadb.namespace }}
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
