apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: {{ .Values.wordpress.namespace }}
type: Opaque
data:
  mysql-password: {{ .Values.wordpress.secrets.mariadb_password }}
  wordpress-password: {{ .Values.wordpress.secrets.wordpress_password }}
