apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: {{ .Values.wordpress.namespace }}
spec:
  selector:
    app: wordpress
  type: {{ .Values.wordpress.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.wordpress.service.port }}
      targetPort: {{ .Values.wordpress.service.targetPort }}
